market/urls.py
from django.urls import path
from . import views

urlpatterns = [ # ip주소/market/
    # CBV
    path('', views.GoodsList.as_view()),
    path('<int:pk>/', views.GoodsDetail.as_view()),  # IP주소/market/1

    # 다대일 Category
    path('category/<str:slug>/', views.category_page),  # IP주소/market/category/slug

    # 다대일 제조사
    path('maker/<str:slug>/', views.maker_page),  # IP주소/market/maker/slug

    # 다대다 Tag
    path('tag/<str:slug>/', views.tag_page),    # IP주소/market/tag/slug

    # 상품 등록/수정 Form
    path('create_goods/', views.GoodsCreate.as_view()),   # IP주소/market/create_goods
    path('update_goods/<int:pk>/', views.GoodsUpdate.as_view()),  # IP주소/market/update_goods/1

    # 댓글 Comment Form
    path('<int:pk>/new_comment/', views.new_comment),  # IP주소/blog/post의 pk/new_comment/
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),  # IP주소/blog/update_comment/1 : comment의 pk

    # 검색 기능 - 검색어: 'q'uery
    path('search/<str:q>/', views.GoodsSearch.as_view()),  # IP주소/search/검색어

    # 댓글 삭제
    path('delete_comment/<int:pk>/', views.delete_comment), # IP주소/market/delete_comment/1 : comment의 pk

]

myShoppingmall/urls.py
from django.contrib import admin
from django.urls import path, include

# 정적파일: url 처리
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),  # IP주소/admin
    path('market/', include('market.urls')),  # IP주소/market
    path('', include('single_pages.urls')),  # IP주소/

    # allauth에서 제공하는 url => migrate만!
    path('accounts/', include('allauth.urls')),  # IP주소/accounts/
]

# 미디어 파일을 위한 url 지정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/models.py
import os
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# 모델 구현

# 다대다 : 태그 모델
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    # p.tag
    def __str__(self):
        return self.name

    # p.get_absolute_url
    def get_absolute_url(self):
        return f'/market/tag/{self.slug}'



# 다대일 : 카테고리 모델 - SlugField
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True) # 고유값
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)  # unicode: 한글 사용

    # p.category 객체 요청 > 문자열 반환
    def __str__(self):
        return self.name

    # p.get_absolute_url
    def get_absolute_url(self):
        return f'/market/category/{self.slug}/'

    # 클래스 안의 클래스: 특정 값을 지정
    class Meta:
        verbose_name_plural = 'Categories'


# 다대일 : 제조사 모델 - SlugField
class Maker(models.Model):
    name = models.CharField(max_length=50, unique=True) # 고유값
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)  # unicode: 한글 사용
    address = models.TextField()    # 주소
    phone = models.CharField(max_length=20, unique=True) # 연락처 - 고유값
    website = models.CharField(max_length=100, unique=True) # 웹사이트 url

    # p.maker 객체 요청 > 문자열 반환
    def __str__(self):
        return self.name

    # p.get_absolute_url
    def get_absolute_url(self):
        return f'/market/maker/{self.slug}/'

    # 클래스 안의 클래스: 특정 값을 지정
    class Meta:
        verbose_name_plural = 'Makers'




# 상품(Goods) 모델
class Goods(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True) # 미리보기 글 # char: 제한 가능 / text: 제한X
    content = models.TextField()

    price = models.IntegerField(default=10000) # 가격

    created_at = models.DateTimeField(auto_now_add=True)  # 새로 작성 시 auto_now_add
    updated_at = models.DateTimeField(auto_now=True)  # 수정(업데이트) 시 auto_now

    head_image = models.ImageField(upload_to='market/images/%Y/%m/%d/', blank=True)

    # => 다대일 관계: ForeignKey() 사용         # on_delete=models.CASCADE : user 삭제되면 > goods도 같이 없어진다
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL) # <- 괄호() X
                                    # null=True 반드시 필요 // SET_NULL: user가 삭제되면 null(none)로 바꿈 >> goods 그대로 유지
    # 다대일: 제조사 & 카테고리
    maker = models.ForeignKey(Maker, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
                                                    # blank: admin/form에서 공란 허용
    # 다대다 관계: 태그
    tags = models.ManyToManyField(Tag, blank=True) # null 설정, on_delete 설정 할 필요 X 이미 되어있음


    def __str__(self):
       return f'[{self.pk}] {self.title}::{self.author} _ {self.created_at}' # ex) [1] Goods_title_1::작성자  2022.01.01 00:00:00

    def get_absolute_url(self):
        return f'/market/{self.pk}/'

    # 아바타 이미지
    def get_avatar_url(self):
        if self.author.socialaccount_set.exists(): # 여러 개의 소셜 계정으로 로그인 시
            return self.author.socialaccount_set.first().get_avatar_url() # 구글
        else: # 이메일/admin 로그인 시
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'



# 댓글 (다대일) - Goods 모델 밑에 작성
class Comment(models.Model):
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)    # 포스트 삭제 시 댓글도 모두 삭제
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 댓글 삭제 시 작성자도 모두 삭제
    content = models.TextField()                            # 댓글 내용 글자 제한 X
    created_at = models.DateTimeField(auto_now_add=True)    # 작성일
    modified_at = models.DateTimeField(auto_now=True)       # 수정일

    def __str__(self):
        return f'{self.author} : {self.content}'    # 작성자 : 댓글내용

    def get_absolute_url(self):
        return f'{self.goods.get_absolute_url()}#comment-{self.pk}' # 샵(#) 뒤: 해당 id 값의 태그로 이동

    # 아바타 이미지
    def get_avatar_url(self):
        if self.author.socialaccount_set.exists(): # 여러 개의 소셜 계정으로 로그인 시
            return self.author.socialaccount_set.first().get_avatar_url() # 구글
        else: # 이메일/admin 로그인 시
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

market/forms.py
# 댓글폼 Comment Form
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta: # 클래스 안의 클래스
        model = Comment
        fields = ('content', )  # 폼에서 [댓글내용]만 사용

market/views.py
from django.shortcuts import render, redirect
from .models import Goods, Category, Tag, Comment, Maker
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q


# 댓글 삭제 기능
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    goods = comment.goods
    # 삭제 다시 확인
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(goods.get_absolute_url())
    else:
        PermissionDenied


# Comment Form: 댓글 수정하기
class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    # comment_form.html: UpdateView가 (모델명)_form.html을 템플릿으로 인지

    # 요청 사용자가 권한ㅇ => 댓글 수정하기 페이지 보내기(dispatch)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied  # Exception 발생



# 상품 생성 - Form
class GoodsCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Goods
    fields = ['title', 'hook_text', 'content', 'head_image', 'maker', 'category']

    # goods_form.html: CreateView가 (모델명)_form.html을 템플릿으로 인지

    def get_context_data(self, object_list=None, **kwargs):
        context = super(GoodsCreate, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Goods.objects.filter(category=None).count
        context['makers'] = Maker.objects.all()
        context['no_maker_goods_count'] = Goods.objects.filter(maker=None).count

        return context

    # 폼이 올바른지 확인 (LoginRequiredMixin)
    def form_valid(self, form):
        # 요청하는 사용자 정보
        current_user = self.request.user

        # 인증된 사용자(+슈퍼유저/스탭 (UserPassesTestMixin))인 경우
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            # 해당 사용자를 폼에 해당하는 작성자로 간주
            form.instance.author = current_user
            response = super(GoodsCreate, self).form_valid(form)
            # 태그 입력
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()             # 문자열의 전체 앞뒤 여백 제거
                tags_str = tags_str.replace(',',';')    # [,]->[;]으로 변환 , is_created
                tag_list = tags_str.split(';')          # [;] 기준으로 문자열 분리 >> 배열
                for t in tag_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response             # super(GoodsCreate, self).form_valid(form)
        else:
            return redirect('/market/')   # 인증된 사용자가 아닌 경우 market 페이지로 이동

    # (UserPassesTestMixin)
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff  # 둘 중 하나 해당 시 true 반환



# 이미 존재하는 상품 수정
class GoodsUpdate(LoginRequiredMixin, UpdateView):
    model = Goods
    fields = ['title', 'hook_text', 'content', 'head_image', 'maker', 'category']  # 등록글 속성들, 똑같이 적기 , 'tags'
    template_name = 'market/goods_update_form.html'


    def get_context_data(self, object_list=None, **kwargs):
        context = super(GoodsUpdate, self).get_context_data()
        # 태그 입력 - 기존 태그에 입력한 새 태그 추가
        if self.object.tags.exists:
            tag_str_list = list()
            for t in self.object.tags.all():
                tag_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tag_str_list)
        context['categories'] = Category.objects.all()
        context['no_category_goods_count'] = Goods.objects.filter(category=None).count
        context['makers'] = Maker.objects.all()
        context['no_maker_goods_count'] = Goods.objects.filter(category=None).count
        return context

    # 요청 사용자가 권한ㅇ => 포스트 수정하기 페이지 보내기(dispatch)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(GoodsUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied  # Exception 발생

    def form_valid(self, form):
        response = super(GoodsUpdate, self).form_valid(form)
        self.object.tags.clear()    # 기존 태그들을 삭제 후 새 태그들 등록
        # 태그 입력
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()             # 문자열의 전체 앞뒤 여백 제거
            tags_str = tags_str.replace(',', ';')   # [,]->[;]으로 변환 , is_created
            tag_list = tags_str.split(';')          # [;] 기준으로 문자열 분리 >> 배열
            for t in tag_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response



# CBV: ListView 사용 >> 상품 목록 페이지 만들기
class GoodsList(ListView):
    model = Goods
    # goods_list.html: ListView이 (모델명)_list.html을 템플릿으로 인지

    ordering = '-pk'    # 최신등록순
    paginate_by = 5     # Pagination: 한 페이지에 포스트 n개씩만 보여주기

    # Context 데이터 전달
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GoodsList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_goods_count'] = Goods.objects.filter(category=None).count
        context['makers'] = Maker.objects.all()
        context['no_maker_goods_count'] = Goods.objects.filter(category=None).count
        return context


# 상품 상세 페이지
class GoodsDetail(DetailView):
    model = Goods
    # goods_detail.html: ListView이 (모델명)_detail.html을 템플릿으로 인지

    # 카테고리 context 데이터 전달
    def get_context_data(self, **kwargs):
        context = super(GoodsDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_goods_count'] = Goods.objects.filter(category=None).count
        context['makers'] = Maker.objects.all()
        context['no_maker_goods_count'] = Goods.objects.filter(category=None).count
        context['comment_form'] = CommentForm   # 추가
        return context


# 검색 기능 - GoodsList 밑에 작성
class GoodsSearch(GoodsList): # ListView 상속, goods_list.html
    paginate_by = None

    # 검색어 -> set
    def get_queryset(self):
        q = self.kwargs['q']    # 'q'라는 인자를 받아와서 가져옴
        goods_list = Goods.objects.filter(    # Q: 여러 조건 사용
            Q(title__contains=q) | Q(tags__name__contains=q) # = tags.name.contains(파이썬 문법)
        ).distinct()    # 중복으로 검색되는 요소가 있을 경우, 하나만 남김
        return goods_list

    # Context 데이터 전달
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GoodsSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        return context


# 카테고리 & 제조사 & 태그 & 댓글: GoodsDetail 안x 밖ㅇ (카테고리, 태그 => GoodsList에서도 사용ㅇ)

# CommentForm: 새 댓글 작성하기
def new_comment(request, pk):
    # 로그인한 유저인 경우
    if request.user.is_authenticated:
        goods = get_object_or_404(Goods,pk=pk)

        # 요청 형식이 POST인 경우
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)

            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.goods = goods
                comment.author = request.user
                comment.save() # 서버 model에 save
                return redirect(comment.get_absolute_url()) # 해당 url로 이동
        # 요청 형식이 POST가 아닌 경우 : GET
        else:
            return redirect(goods.get_absolute_url()) # 포스트 상세 페이지로 이동
    # 로그인 X 사용자인 경우
    else:
        raise PermissionDenied


# 다대일: Category 페이지
def category_page(request, slug):  # <- slug: 매개변수로 갖고옴
    if slug == 'no_category':
        category = '미분류'
        goods_list = Goods.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        goods_list = Goods.objects.filter(category=category)

    return render(request, 'market/goods_list.html', {
        'category': category,
        'goods_list': goods_list,  # 미분류 때문에 미리 변수에 할당 / Goods.objects.filter(category=category)
        'categories': Category.objects.all(),
        'no_category_goods_count': Goods.objects.filter(category=None).count,
        'makers': Maker.objects.all(),
        'no_maker_goods_count': Goods.objects.filter(maker=None).count
    })


# 다대일: Maker 페이지
def maker_page(request, slug):  # <- slug: 매개변수로 갖고옴
    if slug == 'no_maker':
        maker = '미분류'
        goods_list = Goods.objects.filter(maker=None)
    else:
        maker = Maker.objects.get(slug=slug)
        goods_list = Goods.objects.filter(maker=maker)

    return render(request, 'market/goods_list.html', {
        # side bar의 categorym, maker
        'categories': Category.objects.all(),
        'no_category_goods_count': Goods.objects.filter(category=None).count,

        'maker': maker,
        'goods_list': goods_list,  # 미분류 때문에 미리 변수에 할당 / Goods.objects.filter(category=category)
        'makers': Maker.objects.all(),
        'no_maker_goods_count': Goods.objects.filter(maker=None).count
    })


# 다대다 : Tag 페이지
def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    goods_list = tag.goods_set.all()

    return render(request, 'market/goods_list.html', {
        'tag': tag,

market/templates/market/comment_form.html
{% extends 'market/base.html' %}

{% load crispy_forms_tags %}

<!-- goods page head title -->
{% block head_title %}
    Edit the Comment - Goods
{% endblock %}

<!-- Featured Market goods -->
{% block main_area %}

<h1>Edit the Comment</h1>
<hr/>

<form method="post" enctype="multipart/form-data">
    <!-- token -->
    {% csrf_token %}

    {{ form | crispy }} <!-- view.py의 fields > models.py에 내용 있음 -->

    <button type="submit" class="btn btn-primary float-right">Submit</button>
</form>

{% endblock %}

market/templates/market/goods_detail.html
{% extends 'market/base.html' %}
{% load crispy_forms_tags %}

<!-- goods page head title -->
{% block head_title %}
    {{ goods.title }} - Market
{% endblock %}

<!-- Featured Market goods-->
{% block main_area %}
<!-- Goods content-->
    <div id="goods-area">
        <!--  Header-->
        <header class="mb-4">
            <!--  Title-->
            <h1 class="fw-bolder mb-1">{{ goods.title | lower }}</h1>
            {% if goods.hook_text %}
            <h5 class="text-muted">{{ goods.hook_text }}</h5>
            {% endif %}

            <!--  meta content-->
            <div class="text-muted fst-italic mb-2">
                Posted on {{ goods.created_at | date:"Y-m-d h:m:s" }} by {{ goods.author | upper }} <!-- upper 처리 >> test 가능 -->
            </div>

            <!--  Categories-->
            {% if goods.category %}
                <a class="badge bg-secondary text-decoration-none link-light"
                   href="{{ goods.category.get_absolute_url }}">
                    {{ goods.category }}
                </a>
            {% else %}
                <a class="badge bg-secondary text-decoration-none link-light"
                   href="/market/category/no_category/">
                    미분류
                </a>
            {% endif %}

            <!--  Makers -->
            {% if goods.maker %}
                <a class="badge bg-secondary text-decoration-none link-light"
                   href="{{ goods.maker.get_absolute_url }}">
                    {{ goods.maker }}
                </a>
            {% else %}
                <a class="badge bg-secondary text-decoration-none link-light"
                   href="/market/maker/no_maker/">
                    미분류
                </a>
            {% endif %}

        </header>

        <!-- Edit Button -->
        <!--user.is_authenticated : 로그인되어 있는지-->
        {% if user.is_authenticated and user == goods.author %}
            <a class="btn btn-info float-right" href="/market/update_goods/{{ goods.pk }}/" role="button">
                <i class="fas fa-pen">Edit Goods</i>
            </a>
        {% endif %}

        <!-- Preview image figure-->
        <figure class="mb-4">
            {% if goods.head_image %}
            <img class="img-fluid rounded" src="{{ goods.head_image.url }}" alt="{{ goods.title }}의 head_image" />
            {% else %}
            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{ goods.pk }}/800/450" alt="random image" />
            {% endif %}
        </figure>

        <!--  content-->
        <div class="mb-5">
            <p class="fs-5 mb-4">{{ goods.content }}</p>

            <!--  Tag -->
            {% if goods.tags.exists %}
                <i class="fas fa-tag"></i>
                {% for t in goods.tags.iterator %}
                    <span class="badge badge-pill badge-light">
                        <a href="{{ t.get_absolute_url }}">#{{ t }}</a>
                    </span>
                {% endfor %}
            {% endif %}
            <br><br>

            <h3>가격: {{ goods.price }}원</h3>

        </div>
    </div>



<!-- Comments section-->
    <div class="mb-5" id="comment-area">
        <div class="card bg-light">
            <div class="card-body">

                <!-- Comment form : 댓글 입력란 -->
<!--                <form class="mb-4">-->

                    <!-- 로그인을 해야 댓글 입력 가능 -->
                    {% if user.is_authenticated %}
<!--                        <textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea>-->
                        <!-- Crispy Form -->
                        <form class="mb-4" id="comment-form" method="post" action="{{goods.get_absolute_url}}new_comment/"> <!-- action: href 같은 역할 -->
                            {% csrf_token %}
                            <div class="form-group">
                                {{ comment_form | crispy }} <!-- views.py의 context -->
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    {% else %}
                        <!-- 로그인 버튼 -->
                        <a role="button" class="btn btn-dark btn-block btn-sm" href="#"
                            data-toggle="modal" data-target="#loginModal">   <!-- navbar의 Login Modal 창 이용 (해당 id값) -->
                            Login and Leave a comment
                        </a>
                    {% endif %}
<!--               </form>-->

                <!-- Single comment : 댓글 -->
                {% if goods.comment_set.exists %} <!-- goods의 댓글 : goods.comment_set -->
                    {% for comment in goods.comment_set.iterator %} <!-- 반복: iterator -->
                        <div class="media d-flex" id="comment-{{comment.pk}}"> <!-- class: 맨 앞에 media 추가 -->
<!--                            <div class="flex-shrink-0">-->
<!--                                <img class="rounded-circle mr-3" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="user's profile image"/>-->
                                <img class="rounded-circle mr-3" src="{{ comment.get_avatar_url }}" alt="{{ comment.author }}" width="30px"/>
<!--                            </div>-->
                            <div class="media-body ms-3"> <!-- class: 맨 앞에 media-body 추가 -->
                                <!-- 로그인 한 사용자인 경우: 댓글 수정 기능 -->
                                {% if user.is_authenticated and comment.author == user %}
                                    <div class="float-right">
                                        <a role="button" class="btn btn-sm btn-info float-right"
                                           href="/market/update_comment/{{comment.pk}}/">
                                            Edit
                                        </a>
                                        <a role="button" class="btn btn-sm btn-danger float-right"
                                           href="#" data-toggle="modal" data-target="#deleteModal-{{comment.pk}}">
                                            Delete
                                        </a>
                                    </div>

                                <!-- Modal -->
                                <div class="modal fade" id="deleteModal-{{comment.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">

                                            <!-- Modal Header -->
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Are you sure to delete?</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                  <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>

                                            <!-- Modal Body -->
                                            <div class="modal-body">
                                                <del>{{ comment | linebreaks }}</del>
                                            </div>

                                            <!-- Modal Footer -->
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                <a role="button" class="btn btn-secondary"
                                                   href="/market/delete_comment/{{comment.pk}}/">
                                                    Delete
                                                </a>
                                            </div>
                                      </div>
                                    </div>
                                </div>

                                {% endif %}

                                <div class="fw-bold">
                                    {{ comment.author.username }}
                                    <small class="text_muted">{{ comment.created_at }}</small>
                                </div>
                                <p>{{ comment.content | linebreaks }}</p> <!-- linebreaks : ㄴ> 줄바꿈 표시 -->

                                <!-- 댓글 수정 시 수정된 시간 출력-->
                                {% if comment.created_at != comment.modified_at %}
                                    <p class="text-muted float-right">
                                        <small>Updated: {{ comment.modified_at }}</small>
                                    </p>
                                {% endif %}

                            </div>
                        </div>
                    {% endfor %}
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

market/templates/market/goods_form.html
{% extends 'market/base.html' %}
{% load crispy_forms_tags %}

<!-- market page head title -->
{% block head_title %}
    Create a Goods - Market
{% endblock %}

{% block main_area %}

<h1>Create a New Goods</h1>
<hr/>

<form method="post" enctype="multipart/form-data">
    <!-- token -->
    {% csrf_token %}

    <!-- view.py의 fields > models.py에 내용 있음 -->
        {{ form | crispy }}  <!-- form이 없으면 crispy 적용 -->

        <!-- 태그 입력: [,], [;] 으로 구분 -->
        <!-- select -> text 입력창으로 변환 -->

        <!-- crispy form -->
        <div id="div_id_tags_str">
            <label for="id_tags">Tags: </label>
            <input id="id_tags" type="text" name="tags_str" class="textinput textInput form-control">
        </div>

    <button type="submit" class="btn btn-primary float-right">Submit</button>

</form>

{% endblock %}

market/templates/market/goods_update_form.html
{% extends 'market/base.html' %}
{% load crispy_forms_tags %}

<!-- goods page head title -->
{% block head_title %}
    Update the Goods - Market
{% endblock %}

{% block main_area %}

<h1>Update the Goods</h1>
<hr/>

<form method="post" enctype="multipart/form-data">
    <!-- token -->
    {% csrf_token %}
        {{ form | crispy }} <!-- view.py의 fields > models.py에 내용 있음 -->

        <!-- 태그 입력: [,], [;] 으로 구분 -->
        <!-- select -> text 입력창으로 변환 -->
        <!-- crispy form -->
        <div id="div_id_tags_str">
            <label for="id_tags">Tags: </label>
            <input id="id_tags" type="text" name="tags_str" value="{{ tags_str_default }}"
                   class="textinput textInput form-control">
        </div>

    <button type="submit" class="btn btn-primary float-right">Submit</button>
</form>

{% endblock %}